
# *************************************************************
#
# The OpenTRV project licenses this file to you
# under the Apache Licence, Version 2.0 (the "Licence");
# you may not use this file except in compliance
# with the Licence. You may obtain a copy of the Licence at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the Licence is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the Licence for the
# specific language governing permissions and limitations
# under the Licence.
#
# *************************************************************
# Author(s) / Copyright (s): Mark Hill 2017
#                            Deniz Erbilgin 2017
#                            Damon Hart-Davis 2017
sudo: false
language: cpp
env: PATH=$PWD/arduino-1.8.1:$PATH
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16 -extension RANDR"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.1-linux64.tar.xz
  - wget https://github.com/opentrv/OTRadioLink/archive/master.zip
  - wget https://github.com/opentrv/OTAESGCM/archive/master.zip
  - tar xf arduino-1.8.1-linux64.tar.xz
  - unzip master.zip
  - unzip master.zip.1
#  - sudo mv arduino-1.8.1 /usr/local/share/arduino
#  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ls -al
  - arduino --pref "boardsmanager.additional.urls=https://raw.githubusercontent.com/opentrv/OpenTRV-Config/master/Arduino/package_opentrv_index.json" --save-prefs
  - arduino --install-boards "opentrv:avr"
  - arduino --pref "boardsmanager.additional.urls=" --save-prefs
  - ln -s $PWD/OTAESGCM-master/content/OTAESGCM $PWD/Arduino/libraries/OTAESGCM
  - ln -s $PWD/OTRadioLink-master/content/OTRadioLink $PWD/Arduino/libraries/OTRadioLink
  - ls -al Arduino/libraries
  - sudo mv arduino-1.8.1 /usr/local/share/arduino  # Test sudo disabled

script:
  - arduino --verify --board opentrv:avr:opentrv_v0p2 $PWD/Arduino/V0p2_Main/V0p2_Main.ino
  - ./V0p2_primary_CONFIGs_compile_tests.sh
  - ./V0p2_minimal_hw_compilation_tests.sh
notifications:
  email:
    recipients:
      - ci@opentrv.uk
    on_success: change
    on_failure: always
  irc:
    channels: "irc.z.je#opentrv"
    on_success: change
    on_failure: change
